name: Update Databricks Secret
on:
  push:
    branches:
      - main
# on:
#   schedule:
#     - cron: '*/5 * * * *'

jobs:
  update-secret:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    # Install databricks CLI as per https://docs.databricks.com/dev-tools/cli/databricks-cli.html
    - name: Install databricks CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-identity azure-keyvault-secrets requests

    - name: Retrieve secrets from Azure Key Vault
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_KEY_VAULT_NAME: ${{ secrets.AZURE_KEY_VAULT_NAME }}
      run: |
        echo "Retrieving secrets from Azure Key Vault..."
        python -c "
        import os

        from azure.identity import DefaultAzureCredential
        from azure.keyvault.secrets import SecretClient

        key_vault_name = os.getenv('AZURE_KEY_VAULT_NAME')
        key_vault_uri = f'https://{key_vault_name}.vault.azure.net'

        credential = DefaultAzureCredential()
        client = SecretClient(vault_url=key_vault_uri, credential=credential)

        storage_account_name = client.get_secret('cdv-big-data-sa-name').value
        storage_account_key = client.get_secret('cdv-big-data-sa-key').value

        with open(os.getenv('GITHUB_ENV'), 'a') as env_file:
            env_file.write(f'STORAGE_ACCOUNT_NAME={storage_account_name}\n')
            env_file.write(f'STORAGE_ACCOUNT_KEY={storage_account_key}\n')
        "

    - name: Update Databricks Secret
      env:
        STORAGE_ACCOUNT_NAME: ${{ env.STORAGE_ACCOUNT_NAME }}
        STORAGE_ACCOUNT_KEY: ${{ env.STORAGE_ACCOUNT_KEY }}
      run: |
        echo "Updating secret in Databricks..."
        databricks -v
        databricks secrets secrets put-secret CDV-BIG-DATA cdv-big-data-sa-name $STORAGE_ACCOUNT_KEY
        databricks secrets secrets put-secret CDV-BIG-DATA cdv-big-data-sa-key $STORAGE_ACCOUNT_NAME
    