name: Update Databricks Secret

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  update-secret:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-identity azure-keyvault-secrets requests databricks-cli

    - name: Retrieve secrets from Azure Key Vault
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_KEY_VAULT_NAME: ${{ secrets.AZURE_KEY_VAULT_NAME }}
      run: |
        echo "Retrieving secrets from Azure Key Vault..."
        python -c "
        import os
        from azure.identity import DefaultAzureCredential
        from azure.keyvault.secrets import SecretClient

        key_vault_name = os.getenv('AZURE_KEY_VAULT_NAME')
        key_vault_uri = f'https://{key_vault_name}.vault.azure.net'

        credential = DefaultAzureCredential()
        client = SecretClient(vault_url=key_vault_uri, credential=credential)

        databricks_host = client.get_secret('cdv-big-data-adb-url').value
        databricks_token = client.get_secret('cdv-big-data-adb-token').value
        storage_account_key = client.get_secret('cdv-storage-account-key').value

        with open(os.getenv('GITHUB_ENV'), 'a') as env_file:
            env_file.write(f'DATABRICKS_HOST={databricks_host}\n')
            env_file.write(f'DATABRICKS_TOKEN={databricks_token}\n')
            env_file.write(f'STORAGE_ACCOUNT_KEY={storage_account_key}\n')
        "

    - name: Update Databricks Secret
      env:
        STORAGE_ACCOUNT_NAME: ${{ env.storage_account_name }}
        STORAGE_ACCOUNT_KEY: ${{ env.storage_account_key }}
      run: |
        echo "Updating secret in Databricks..."
        databricks secrets put --scope my-scope --key storage-account-key --string-value $STORAGE_ACCOUNT_KEY
        databricks secrets put --scope my-scope --key storage_account_name --string-value $STORAGE_ACCOUNT_NAME